name = "tinygo-server"
main = "./js/worker.mjs"
compatibility_date = "2022-05-15"
compatibility_flags = [
    "streams_enable_constructors"
]

[build]
command = "tinygo build -o dist/app.wasm -target wasm ./main.go"
